// apps/website/components/form/Select.vue
<script setup lang="ts">
import {
  Listbox,
  ListboxButton,
  ListboxOptions,
  ListboxOption,
  ListboxLabel,
} from "@headlessui/vue";
import { css, cx } from "styled-system/css";
import { token } from "styled-system/tokens";

import type { SelectOption } from "~/types/form";

interface Props {
  label?: string;
  options: SelectOption[];
  placeholder: string;
}

defineProps<Props>();

const selectedValue = defineModel<string | undefined>({
  required: true,
});

const minWidth = "160px";

const triggerCss = css({
  alignItems: "center",
  backgroundColor: token("colors.surface"),
  borderColor: token("colors.border"),
  borderRadius: "sm",
  borderWidth: "1px",
  cursor: "pointer",
  display: "flex",
  minWidth: minWidth,
  gap: "8px",
  px: "xs",
  py: "xxs",
  outline: "none",
  textAlign: "left",

  _hover: {
    borderColor: token("colors.primary"),
  },
  _expanded: {
    borderColor: token("colors.primary"),
  },
});

const optionsCss = css({
  backgroundColor: token("colors.surface"),
  borderColor: token("colors.primary"),
  borderRadius: "sm",
  borderWidth: "1px",
  boxShadow: token("shadows.subtle"),
  minWidth: minWidth,
  marginTop: "4px",
  padding: "xxs",
  position: "absolute",
  zIndex: 100,
  outline: "none",
  overflow: "auto",
  maxHeight: "60vh",
});

const itemCss = css({
  cursor: "default",
  px: "xs",
  py: "4px",
  borderRadius: "xs",
  outline: "none",
  userSelect: "none",

  "&[data-headlessui-state*='active']": {
    backgroundColor: token("colors.selection"),
  },
  _disabled: {
    color: token("colors.font.muted"),
  },
});
</script>

<template>
  <Listbox
    :model-value="selectedValue ?? ''"
    @update:model-value="(value: string | null) => (selectedValue = value ?? undefined)"
  >
    <div>
      <ListboxLabel v-if="label">
        <Text size="sm">{{ label }}</Text>
      </ListboxLabel>
      <div :class="css({ position: 'relative' })">
        <ListboxButton :class="cx(triggerCss)">
          <span
            :class="
              css({ flex: 1, truncate: true, color: !selectedValue ? 'gray.400' : 'inherit' })
            "
          >
            {{ selectedValue || placeholder }}
          </span>
          <icon name="mynaui:chevron-down" />
        </ListboxButton>

        <ListboxOptions :class="optionsCss" :style="{ '--anchor-gap': '5px' }">
          <ListboxOption
            v-for="option in options"
            :key="option.value"
            :disabled="option.disabled"
            :value="option.value"
            as="template"
          >
            <div :class="itemCss">
              {{ option.label }}
            </div>
          </ListboxOption>
        </ListboxOptions>
      </div>
    </div>
  </Listbox>
</template>

// apps/website/src/components/ui/select.tsx
import { Listbox, ListboxButton, ListboxOption, ListboxOptions } from "@headlessui/react";

export type SelectOption = {
  value: string;
  label: string;
  disabled?: boolean;
};

type SelectProps = {
  label: string;
  options: SelectOption[];
  value?: string;
  disabled?: boolean;
  onChange: (value: string | undefined) => void;
};

export const Select = (props: Readonly<SelectProps>) => {
  const selected = props.options.find((option) => option.value === props.value);
  const buttonLabel = selected?.label ?? props.label;

  return (
    <Listbox
      value={props.value ?? ""}
      disabled={props.disabled}
      onChange={(nextValue) => {
        const next = typeof nextValue === "string" && nextValue.length > 0 ? nextValue : undefined;
        props.onChange(next);
      }}
    >
      <div className="relative inline-flex min-w-[170px]">
        <ListboxButton
          className="inline-flex w-full items-center justify-between rounded-full border border-[color:var(--color-border)]/45 bg-[color:var(--color-surface)] px-4 py-2 text-left text-sm font-medium hover:border-[color:var(--color-primary)]/45 focus:outline-none focus:ring-0 disabled:cursor-not-allowed disabled:opacity-45 disabled:hover:border-[color:var(--color-border)]/45"
          aria-label={props.label}
        >
          <span className="truncate">{buttonLabel}</span>
          <span className="ml-2 text-xs">▾</span>
        </ListboxButton>
        <ListboxOptions
          anchor="bottom start"
          portal
          modal={false}
          className="z-50 mt-2 max-h-72 w-[220px] overflow-auto rounded-md border border-black/10 bg-[color:var(--color-surface)] p-2 shadow-lg outline-none"
        >
          <ListboxOption
            value=""
            className="mb-1 cursor-pointer rounded-md px-2 py-1.5 text-sm data-[focus]:bg-[color:var(--color-surface-soft)]"
          >
            Any {props.label}
          </ListboxOption>
          {props.options.map((option) => (
            <ListboxOption
              key={option.value}
              value={option.value}
              disabled={option.disabled}
              className="mb-1 cursor-pointer rounded-md px-2 py-1.5 text-sm data-[disabled]:cursor-not-allowed data-[disabled]:opacity-45 data-[focus]:bg-[color:var(--color-surface-soft)]"
            >
              {option.label}
            </ListboxOption>
          ))}
        </ListboxOptions>
      </div>
    </Listbox>
  );
};
